defaultEntryPoints = ["http", "https"]
InsecureSkipVerify = true 

logLevel = "ERROR"

# Set to log to file rather than (default STDOUT). Comment out to sendo Graylog.
[traefikLog]
  filePath = "/etc/traefik/traefik.log"

#[accessLog]
#  filePath = "/etc/traefik/access.log"

#  [accessLog.filters]
#    statusCodes = ["200", "300-302"]
#    retryAttempts = true
#    minDuration = "10ms"

[entryPoints]
  [entryPoints.http]
   address = ":80"
    [entryPoints.http.forwardedHeaders]
      trustedIPs = ["172.0.0.1/8", "10.0.0.1/8"]	  
    [entryPoints.http.redirect]
      entryPoint = "https"
 [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
	  
[retry]

[api]
  entrypoint = "traefik"
  dashboard = true

[docker]
  endpoint = "tcp://127.0.0.1:2375"
  domain = "gkoerk.com"
  watch = true
  exposedbydefault = false

[acme]
  email = "gkoerk@gmail.com"  
  storage = "/etc/traefik/acme.json"  
  entryPoint = "https"  
  #acmeLogging = true
  onHostRule = true
  #onDemand = true
  #caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  #[acme.httpChallenge]
  #entryPoint = "http"

[acme.dnsChallenge]
  provider = "namecheap"
  resolvers = ["1.1.1.1:53", "8.8.8.8:53"]

[[acme.domains]]
  main = "*.gkoerk.com"
  sans = ["gkoerk.com"]
[[acme.domains]]
  main = "*.qnapunofficial.com"
  sans = ["qnapunofficial.com"]
[[acme.domains]]
  main = "*.oracleoptimizer.com"
  sans = ["oracleoptimizer.com"]  

[file]
  watch=true

[frontends]
  
  [frontends.pihole]
    backend="pihole"
    passHostHeader = true
	
	[frontends.pihole.routes.1]
	  rule = "Host:pihole.gkoerk.com; AddPrefix: /admin"

  [frontends.unifi]
    backend="unifi"
    passHostHeader = true
    
	[frontends.unifi.routes.1]
	  rule = "Host:unifi.gkoerk.com"
	  port = 8443
	  protocol = "https"

  [frontends.transmission]
    backend="transmission"
    passHostHeader = true
    
	[frontends.transmission.routes.1]
	  rule = "Host:transmission.gkoerk.com"
	  
	  
[backends]

  [backends.pihole]
    [backends.pihole.servers.pihole]
	  url = "http://192.168.1.2:80"
	  weight = 1

  [backends.unifi]
    [backends.unifi.servers.unifi]
	  url = "https://192.168.1.10:8443"
	  weight = 1
	certFile = "/etc/traefik/ssl/gkoerk.crt"
	keyFile = "/etc/traefik/ssl/gkoerk.key"

  [backends.transmission]
    [backends.transmission.servers.transmission]
	  url = "http://192.168.1.2:80"
	  weight = 1
