# Diskover Recipe
# /share/appdata/config/diskover/diskover.yml
version: "3.4"

services:
  diskover:
    image: linuxserver/diskover:latest
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASS=R7gc87y4
      - RUN_ON_START=true
      - USE_CRON=true
      - INDEX_NAME=diskover-
    volumes:
      - /share/appdata/diskover/config:/config
      - /share:/data
# Or, you can bind multiple host directories under the /data directory for scanning.
      #- /share/Photos:/data/photos
      #- /share/downloads:/data/downloads
      #- /share/appdata:/data/appdata
    networks:
      - internal
      - traefik_public
    deploy:
      resources:
        limits:
          memory: 4096M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.diskover.entrypoints=https"
        - "traefik.http.routers.diskover.rule=Host(`diskover.gkoerk.com`)"
        - "traefik.http.routers.diskover.tls.certresolver=namecheap"
        - "traefik.http.routers.diskover.middlewares=forward-auth@file"
        - "traefik.http.routers.diskover.service=diskover"
        - "traefik.http.services.diskover.loadbalancer.server.port=80"
        - "traefik.http.routers.diskoverdash.entrypoints=https"
        - "traefik.http.routers.diskoverdash.rule=Host(`diskoverdash.gkoerk.com`)"
        - "traefik.http.routers.diskoverdash.tls.certresolver=namecheap"
        - "traefik.http.routers.diskoverdash.middlewares=forward-auth@file"
        - "traefik.http.routers.diskoverdash.service=diskoverdash"
        - "traefik.http.services.diskoverdash.loadbalancer.server.port=9181"
        - "traefik.http.routers.diskoversocket.entrypoints=https"
        - "traefik.http.routers.diskoversocket.rule=Host(`diskoverdash.gkoerk.com`)"
        - "traefik.http.routers.diskoversocket.tls.certresolver=namecheap"
        - "traefik.http.routers.diskoversocket.middlewares=forward-auth@file"
        - "traefik.http.routers.diskoversocket.service=diskoversocket"
        - "traefik.http.services.diskoversocket.loadbalancer.server.port=9999"

  elasticsearch:
    image: elasticsearch:5.6-alpine
    volumes:
      - /share/runtime/diskover/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 2048M

  redis:
    image: redis:alpine
    volumes:
      - /share/runtime/diskover/redis:/data
    networks:
      - internal

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.53.0/24
