[http]
  [http.routers]
    [http.routers.https-redirect]
	  entrypoints = ["http", "https"]
	  rule = "HostRegexp(`{any:.*}`)"
	  middlewares = ["https-redirect"]
	  service = "default"  
  
    [http.routers.gkoerk]
      rule = "Host(`gkoerk.com`)"
	  middlewares = ["https-redirect"]
	  entrypoints = ["http", "https"]
	  service = "default"	  
	  [http.routers.gkoerk-http.tls]
	    certResolver = "namecheap"
	    [[http.routers.gkoerk-http.tls.domains]]
		  main = "*.gkoerk.com"
		  sans = ["gkoerk.com"]
		  
  [http.middlewares]
    [http.middlewares.secured.chain]
      middlewares = ["forward-auth", "https-redirect"]
#    [http.middlewares.compress.compress]
    [http.middlewares.forward-auth.forwardAuth]
      address = "http://192.168.1.100:8080/authorize"
	  trustForwardHeader = true
      authResponseHeaders = ["X-FORWARDAUTH-NAME", "X-FORWARDAUTH-SUB", "X-FORWARDAUTH-EMAIL"]
#	  insecureSkipVerify = true
    [http.middlewares.https-redirect.redirectScheme]
      scheme = "https"
    [http.middlewares.basic-user.basicAuth]
      users = ["user:password-from-htpasswd"]	  
#    [http.middlewares.known-ips.ipWhiteList]
#      sourceRange = ["172.0.0.1/8", "10.0.0.1/8"]

  [http.services]
    [http.services.default]
      [http.services.default.loadBalancer]

        [[http.services.default.loadBalancer.servers]]
          url = "http://127.0.0.1:8080"
