[global]
  checkNewVersion = true

[serversTransport]
  insecureSkipVerify = true
  #rootCAs = ["gkoerk.com"]
  #maxIdleConnsPerHost = 20
  #[serversTransport.forwardingTimeouts]
    #dialTimeout = 42
    #responseHeaderTimeout = 42
    #idleConnTimeout = 42
	
[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.forwardedHeaders]
      trustedIPs = ["172.0.0.1/8", "10.0.0.1/8"]	
  [entryPoints.https]
    address = ":443"

[providers]
  [providers.docker]	
	endpoint = "unix:///var/run/docker.sock"	
	watch = true
    swarmMode = true
    network = "traefik_public"
	defaultRule = "Host(`{{ .Name }}.gkoerk.com`)"
    useBindPortIP = false
	exposedByDefault = false

  [providers.file]
    filename = "/etc/traefik/dynamic-conf.toml"
    watch = true

[api]
  dashboard = true
  insecure = true
  
[metrics]
  [metrics.prometheus]
    buckets = [0.1,0.3,1.2,5.0]
	addEntryPointsLabels = true
	addServicesLabels = true
	entryPoint = "metrics"

[ping]
  entryPoint = "ping"

[log]
  level = "ERROR"
  filePath = "/etc/traefik/traefik.log"

[accessLog]
  filePath = "/etc/traefik/access.log"
#  bufferingSize = 100

[certificatesResolvers.namecheap.acme]
  email = "gkoerk@gmail.com"
#  caserver=https://acme-staging-v02.api.letsencrypt.org/directory"	  
  storage = "/etc/traefik/acme.json"
  [certificatesResolvers.namecheap.acme.dnsChallenge]
    provider = "namecheap"
	resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
	delayBeforeCheck = 0
