version: "3.4"

services:
  nextcloud:
    image: nextcloud:latest
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=
      - NEXTCLOUD_TRUSTED_DOMAINS=gkoerk.com
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=db_username
      - MYSQL_PASSWORD=db_password
      - REDIS_HOST=redis
      - REDIS_HOST_PORT:6379
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.frontend.rule=Host:nextcloud.gkoerk.com
        - traefik.port=80
        - traefik.docker.network=traefik_public  
    volumes:
      - /share/appdata/nextcloud:/var/www/html
      - /share/appdata/nextcloud/apps:/var/www/html/custom_apps
      - /share/appdata/nextcloud/config:/var/www/html/config
      - /share/appdata/nextcloud/data:/var/www/html/data       

  adminer: 
    image: adminer:latest
    networks: 
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.frontend.rule=Host:adminer.gkoerk.com
        - traefik.port=8080
        - traefik.docker.network=traefik_public
        - "traefik.frontend.auth.forward.address=http://192.168.1.100:8080/authorize"
        - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"            

  db:
    image: mariadb:10
    environment:
      # For database backup (keep 7 days daily backups)
      - MYSQL_ROOT_PASSWORD=db_root_password
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=db_username
      - MYSQL_PASSWORD=db_password 
    networks:
      - internal
    volumes:
      - /share/runtime/nextcloud/db:/var/lib/mysql    

  db-backup:
    image: mariadb:10
    environment:
      # For database backup (keep 7 days daily backups)
      - MYSQL_PWD=db_root_password
      - MYSQL_USER=root
      - BACKUP_NUM_KEEP=7
      - BACKUP_FREQUENCY=1d
    volumes:
      - /share/appdata/nextcloud/database-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        mysqldump -h db --all-databases | gzip -c > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.sql.gz
        (ls -t /dump/dump*.sql.gz|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.sql.gz)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    networks:
      - internal     

  redis:
    image: redis:alpine
    networks:
      - internal
    volumes:
      - /share/runtime/nextcloud/redis:/data     

  solr:
    image: solr:6-alpine   
    networks:
      - internal
    volumes:
      - /share/runtime/nextcloud/solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - nextant

  cron:
    image: nextcloud:latest     
    volumes:
      - /share/appdata/nextcloud:/var/www/html
    user: www-data
    networks:
      - internal
    entrypoint: |
      bash -c 'bash -s <<EOF
        trap "break;exit" SIGHUP SIGINT SIGTERM
        while [ ! -f /var/www/html/config/config.php ]; do
          sleep 1
        done
        while true; do
          php -f /var/www/html/cron.php
          sleep 15m
        done
      EOF'     

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.12.0/24
